
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik-proxy
          args: ["--entryPoints.web.address=:80", "--providers.http.endpoint=http://fastapi-watch-service/traefik_dynamic_conf.json"]
          image: traefik:v3.3
          ports:
            - containerPort: 80
      restartPolicy: Always
